# (PART\*) Lab 4 {-}

*Last updated `r Sys.Date()`*

# Applying Open Science Principles {-}

You will be expected to apply some principles of Open Science to your research project. For a brief refresher on Open Science Principles and the Research Workflow see the following links:

* [Open Science & Registered Reports](https://ubco-biology.github.io/BIOL-116-Lab-Manual/open-science.htmlhttps://ubco-biology.github.io/BIOL-116-Lab-Manual/open-science.html)
* [The Research Workflow](https://ubco-biology.github.io/BIOL-116-Lab-Manual/the-research-workflow.html)

For this project, you will follow the stages of a typical registered report and implement the following Open Science practices while working on your project:

* Using appropriate version control on electronic documents and proper file and data management practices throughout the experiment. 
    * Be sure to follow the rules outlined in Chapters 1-5 [File and Data Management](https://ubco-biology.github.io/Procedures-and-Guidelines/file-and-data-management.html) in the UBCO Biology Procedures & Guidelines Document.
* Performing a literature review on your research topic and documenting a list of consulted studies, how they were found, and the strengths, limitations, and weaknesses of each.
* Submitting a research proposal draft with an established a priori hypothesis, experimental design, and plan for presenting and analyzing your data. This will be marked before the experiment implementation phase and TA feedback incorporated into the project as needed. Creating a detailed, thorough plan for your research often takes as much time as running the experiment and collecting and analyzing your data. The more you plan, including anticipating potential problems, the easier the implementation!
* Implementing the study according to your plan, and noting any deviations from that plan (Note: deviations often happen, and that's OK! The key is to document them). These reflections will be submitted for marks.
* Submitting and presenting a poster that details your experiences implementing the research plan (including any changes recorded, justification for changes, analysis of the data, and your interpretation and conclusion).

# Assignment 3: Research Proposal Draft {-}

**Due before the start of your lab the week of February 7th** 

Research proposals should be approximately 5 double-spaced pages.  Each proposal should:

* Provide a brief literature review to contextualize the proposed research **(1-2 pages)**
    * What do you know about the organisms involved
        - What does it need to survive?
        - What temperature is it typically found? 
        - Remember you have to run this experiment in the lab and be able to control for all variables
    *	What do you know about the issue surrounding toxic algal blooms
    * What differences are there between saltwater systems and freshwater systems if any that need to be considered when making inferences from one to another
* Clearly outline the problem and why this is so important.  You will likely need to use the background information to justify the importance **(0.5-1 pages)**
* Provide clear hypotheses 
* Outline the major methods and data collection (including what statistical analyses to be used, when appropriate and a list of materials required).  There should not be any bullet points here **(1 page)**
* References must be provided and on its own page
* Title page is not necessary
* Provide a detailed projected week by week timeline of your research.  The information in this table should include the following and be in chronological order:
    * Start date of experiment (include pilot round if relevant)
    * Data collection dates and how data will be collected
    * Non-data collection dates should be included with a detail of what you expect to be working on.  E.g. you may need to complete a water change or feed your organisms
    * Additional notes may be added in the case where you anticipate there may need to be a change in timeline depending on previous weeks
    * End date of experiment
    * Below is an example format

**Table 1: Projected weekly timeline**

| Date | Activity |	Notes |
| :--- | :--- | :--- |
| **September 13, 2021** | Experimental set up - clean tank, fill with spring water and heat to appropriate temperature and add organisms |
| **September 20th, 2021** | Count organisms using pods from a small sample and estimating total number to provide baseline population size |	May need to readjust environment depending on organism survival |
| **September 27th, 2021** | Add variable - pesticides | May need to adjust amount of pesticides depending on survivability |

**Ideas on Preparing a Research Proposal**

*	Read a lot!  It is important that you have a thorough understanding of the topic.  At the very least you should have at least 3 primary source papers you are referring too throughout your proposal.
*	Discuss your ideas with other students (not just your partner).  Get a feel for what everyone else is doing and the depth they are working in.
*	Start writing early!  Students often make the mistake of starting the night before the proposal is due.  This more than not results in poor submissions and thus lower grades.  You should expect that you will have at least 3 rounds of revisions before you submit.
*	Someone reading your proposal should be able to tell what question(s) you will address, why the topic is interesting and/or important, how you will approach the problem, the types of data you will collect, and how your research will advance the field.

As you work on the draft of your research proposal, be sure to consult the Final Research Proposal marking rubric [here](https://ubco-biology.github.io/BIOL-205-Lab-Manual/research-proposal-rubric.html)!